import type { Metadata } from "next";
import {Instrument_Sans, Instrument_Serif } from "next/font/google";
import "./globals.css";


const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-ins-sans",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400", // Required for Instrument_Serif
  variable: "--font-ins-serif",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} ${instrumentSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
